/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.PharmacyJPanels;

import Business.Business;
import Insurance.InsurancePlans;
import Pharmacy.Medicine;
import Prescription.Prescription;
import UserAccount.UserAccount;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MC
 */
public class PrescriptionsJPanel extends javax.swing.JPanel {

    public Business business;
    public UserAccount userAccount;
    DefaultTableModel prescTableModel;
    
    public PrescriptionsJPanel() {
        initComponents();
    }
    
    public PrescriptionsJPanel(Business business, UserAccount userAccount) {
        initComponents();
        this.business = business;
        this.userAccount = userAccount;
        this.prescTableModel = (DefaultTableModel) prescriptionsTable.getModel();
        
        displayPrescriptions();
    }
    
    public void displayPrescriptions()
    {
        ArrayList<Prescription> ps = this.business.getPrescriptions().getPrescriptions();
        if(ps.size() >= 0) {
            prescTableModel.setRowCount(0);
            for(Prescription p: ps) {
                    Object row[] = new Object[7];
                    row[0] = p.getPrescriptionId();
                    row[1] = p.getDoctor().getFirstName() + ' ' + p.getDoctor().getLastName();
                    row[2] = p.getPatient().getFirstName() + ' ' + p.getPatient().getLastName();
                    row[3] = p.getMedicine().getMedicineName();
                    row[4] = p.getQuantity();
                    row[5] = p.getStatus();
                    row[6] = p.getMedicine().getPrice() * p.getQuantity();
                    prescTableModel.addRow(row);
                } 
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        prescriptionsTable = new javax.swing.JTable();
        fillPresc = new javax.swing.JButton();
        rejectPresc = new javax.swing.JButton();

        prescriptionsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Pres Id", "Doctor", "Patient", "Medicine", "Quantity", "Status", "Total Cost"
            }
        ));
        jScrollPane1.setViewportView(prescriptionsTable);

        fillPresc.setText("Fill");
        fillPresc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillPrescActionPerformed(evt);
            }
        });

        rejectPresc.setText("Reject");
        rejectPresc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectPrescActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fillPresc, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(rejectPresc, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fillPresc)
                    .addComponent(rejectPresc))
                .addContainerGap(307, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fillPrescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillPrescActionPerformed
        int selectedRowIndex = prescriptionsTable.getSelectedRow();
        String medName = prescriptionsTable.getValueAt(selectedRowIndex, 3).toString();
        String pid = prescriptionsTable.getValueAt(selectedRowIndex, 0).toString();
        Prescription ps = this.business.getPrescriptions().findPrescription(pid);
        ps.setStatus("Filled");
        int quantity = Integer.parseInt(prescriptionsTable.getValueAt(selectedRowIndex, 4).toString());
        Medicine m = this.business.getMedicines().findMedicineByName(medName);
        m.setAvailableCount(m.getAvailableCount() - quantity);
        
        displayPrescriptions();
        
    }//GEN-LAST:event_fillPrescActionPerformed

    private void rejectPrescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectPrescActionPerformed
        int selectedRowIndex = prescriptionsTable.getSelectedRow();
        String medName = prescriptionsTable.getValueAt(selectedRowIndex, 3).toString();
        String pid = prescriptionsTable.getValueAt(selectedRowIndex, 0).toString();
        Prescription ps = this.business.getPrescriptions().findPrescription(pid);
        ps.setStatus("Rejected");
        
        displayPrescriptions();
    }//GEN-LAST:event_rejectPrescActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fillPresc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable prescriptionsTable;
    private javax.swing.JButton rejectPresc;
    // End of variables declaration//GEN-END:variables
}
