/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.PatientJPanels;

import Business.Business;
import Doctor.Doctor;
import Hospital.Hospital;
import Insurance.InsurancePlans;
import Patient.Patient;
import UserAccount.UserAccount;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MC
 */
public class InsurancePlansJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InsurancePlansJPanel
     */
    public Business business;
    public UserAccount userAccount;
    DefaultTableModel insPlansTableModel;
    
    public InsurancePlansJPanel(Business business, UserAccount userAccount) {
        initComponents();
        this.business = business;
        this.userAccount = userAccount;
        this.insPlansTableModel = (DefaultTableModel) insPlansTable.getModel();
        
        String patientId = userAccount.getPersonId();
        Patient currentPatient = this.business.getPatients().findPatient(patientId);
        
        if (currentPatient.getInsurancePlan() != null)
        {
            enrollmentStatusLabel.setText(currentPatient.getInsurancePlan().getPlanName());
        }
        else
        {
            enrollmentStatusLabel.setText("Not Enrolled!");
        }
        
        displayInsurancePlans();
    }
    
    public void displayInsurancePlans()
    {
        ArrayList<InsurancePlans> ips = this.business.getInsurancePlans().getPlansDirectory();
        if(ips.size() >= 0) {
            insPlansTableModel.setRowCount(0);
            for(InsurancePlans h: ips) {
                Object row[] = new Object[5];
                row[0] = h.getPlanID();
                row[1] = h.getPlanName();
                row[2] = h.getCostperMonth();
                row[3] = h.getCostperAnnum();
                row[4] = h.getCoveragePercentage();
                insPlansTableModel.addRow(row);
            }
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        insPlansTable = new javax.swing.JTable();
        enrollBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        enrollmentStatusLabel = new javax.swing.JLabel();

        insPlansTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "PlanId", "Name", "CostPerMonth", "Total Cost - Per Year", "Coverage"
            }
        ));
        insPlansTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(insPlansTable);

        enrollBtn.setText("Request to Enroll");
        enrollBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Current Enrollment Status :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(enrollmentStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(enrollBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(371, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(enrollBtn)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(enrollmentStatusLabel))
                .addContainerGap(334, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void enrollBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollBtnActionPerformed
        String patientId = userAccount.getPersonId();
        Patient currentPatient = this.business.getPatients().findPatient(patientId);
        int selectedRowIndex = insPlansTable.getSelectedRow();
        String planId = insPlansTable.getValueAt(selectedRowIndex, 0).toString();
        
        if (currentPatient.getInsurancePlan() != null)
        {
            JOptionPane.showMessageDialog(null, "You are already registered in an insurance plan");
        }
        else
        {
            InsurancePlans ip = this.business.getInsurancePlans().findInsurancePlan(planId);
            this.business.getInsuranceEnrollmentRequests().addEnrollment(currentPatient, ip);
        }
    }//GEN-LAST:event_enrollBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enrollBtn;
    private javax.swing.JLabel enrollmentStatusLabel;
    private javax.swing.JTable insPlansTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
