/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.InsuranceJPanels;

import UI.PatientJPanels.*;
import Business.Business;
import Doctor.Doctor;
import Hospital.Hospital;
import Insurance.InsuranceEnrollment;
import Insurance.InsurancePlans;
import Patient.Patient;
import UserAccount.UserAccount;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MC
 */
public class InsurancePlansJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InsurancePlansJPanel
     */
    public Business business;
    public UserAccount userAccount;
    DefaultTableModel insPlansTableModel;
    
    public InsurancePlansJPanel(Business business, UserAccount userAccount) {
        initComponents();
        this.business = business;
        this.userAccount = userAccount;
        this.insPlansTableModel = (DefaultTableModel) insEnrollmentsTable.getModel();
        
        displayInsurancePlans();
    }
    
    public void displayInsurancePlans()
    {
        ArrayList<InsuranceEnrollment> ips = this.business.getInsuranceEnrollmentRequests().getEnrollments();
        if(ips.size() >= 0) {
            insPlansTableModel.setRowCount(0);
            for(InsuranceEnrollment h: ips) {
                Object row[] = new Object[5];
                row[0] = h.getEnrollmentId();
                row[1] = h.getPatient().getId();
                row[2] = h.getPatient().getFirstName() + ' ' + h.getPatient().getLastName();
                row[3] = h.getInsurancePlan().getPlanName();
                row[4] = h.getStatus();
                insPlansTableModel.addRow(row);
            }
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        insEnrollmentsTable = new javax.swing.JTable();
        approveBtn = new javax.swing.JButton();
        enrollmentStatusLabel = new javax.swing.JLabel();
        rejectBtn = new javax.swing.JButton();

        insEnrollmentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Enrollment Id", "PatientId", "Patient Name", "Plan Name", "Status"
            }
        ));
        insEnrollmentsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(insEnrollmentsTable);

        approveBtn.setText("Approve");
        approveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveBtnActionPerformed(evt);
            }
        });

        rejectBtn.setText("Reject");
        rejectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(enrollmentStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(approveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(rejectBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(375, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(approveBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rejectBtn)))
                .addGap(70, 70, 70)
                .addComponent(enrollmentStatusLabel)
                .addContainerGap(350, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void approveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveBtnActionPerformed

        int selectedRowIndex = insEnrollmentsTable.getSelectedRow();
        String patientId = insEnrollmentsTable.getValueAt(selectedRowIndex, 1).toString();
        Patient currentPatient = this.business.getPatients().findPatient(patientId);
        
        String enrollmentId = insEnrollmentsTable.getValueAt(selectedRowIndex, 0).toString();
        InsuranceEnrollment ie = this.business.getInsuranceEnrollmentRequests().findEnrollment(enrollmentId);
        
        ie.approveEnrollment(currentPatient);
        displayInsurancePlans();
    }//GEN-LAST:event_approveBtnActionPerformed

    private void rejectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectBtnActionPerformed
        int selectedRowIndex = insEnrollmentsTable.getSelectedRow();
        String patientId = insEnrollmentsTable.getValueAt(selectedRowIndex, 1).toString();
        Patient currentPatient = this.business.getPatients().findPatient(patientId);
        
        String enrollmentId = insEnrollmentsTable.getValueAt(selectedRowIndex, 0).toString();
        InsuranceEnrollment ie = this.business.getInsuranceEnrollmentRequests().findEnrollment(enrollmentId);
        
        ie.rejectEnrollment();
        displayInsurancePlans();
    }//GEN-LAST:event_rejectBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveBtn;
    private javax.swing.JLabel enrollmentStatusLabel;
    private javax.swing.JTable insEnrollmentsTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton rejectBtn;
    // End of variables declaration//GEN-END:variables
}
