/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.DoctorJPanels;

import Business.Business;
import Hospital.Appointment;
import Hospital.Vitals;
import Patient.Patient;
import UserAccount.UserAccount;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MC
 */
public class DoctorVitalsJPanel extends javax.swing.JPanel {

    public Business business;
    public UserAccount userAccount;
    DefaultTableModel vitalsTableModel;
    
    public DoctorVitalsJPanel() {
        initComponents();
    }
    
    public DoctorVitalsJPanel(Business business, UserAccount userAccount) {
        initComponents();
        this.business = business;
        this.userAccount = userAccount;
        this.vitalsTableModel = (DefaultTableModel) docVitalsTable.getModel();
        
        //displayVitals();
        populateDropdowns();
    }
    
    public void populateDropdowns()
    {
        ArrayList<Patient> pts = new ArrayList<Patient>();
        ArrayList<Appointment> aps = this.business.getAppointments().getAppointments();
        for(Appointment a: aps) 
        {
            if (a.getDoctor().getId().equals(userAccount.getPersonId()))
            {
                pts.add(a.getPatient());
            }
        }
        
        for (Patient p : pts)
        {
            selPatientCBox.addItem(p.getId() + ';' + p.getFirstName() + ' ' + p.getLastName());
        }
    }
    
    public void displayVitals(String patientId)
    {
        Patient p = this.business.getPatients().findPatient(patientId);
        ArrayList<Vitals> vitals = p.getVitals().getVitalsList();
        if(vitals.size() >= 0) {
            vitalsTableModel.setRowCount(0);
            for(Vitals v: vitals) {
                Object row[] = new Object[7];
                row[0] = p.getFirstName()+ ' ' + p.getLastName();
                row[1] = v.getVitalId();
                row[2] = v.getBloodPressure();
                row[3] = v.getHeartRate();
                row[4] = v.getWeight();
                row[5] = v.getHeight();
                row[6] = v.getRecordedDate();
                vitalsTableModel.addRow(row);
            }
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        selPatientCBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        docVitalsTable = new javax.swing.JTable();
        findVitalsBtn = new javax.swing.JButton();

        jLabel1.setText("Select a patient");

        docVitalsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient Name", "Vital Id", "BP", "HR", "Weight", "Height", "Recorded Date"
            }
        ));
        jScrollPane1.setViewportView(docVitalsTable);

        findVitalsBtn.setText("Find Vitals");
        findVitalsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findVitalsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(selPatientCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)
                        .addComponent(findVitalsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(530, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(selPatientCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findVitalsBtn))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(363, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void findVitalsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findVitalsBtnActionPerformed
        String patientId = selPatientCBox.getSelectedItem().toString().split(";")[0];
        //Patient p = this.business.getPatients().findPatient(patientId);
        displayVitals(patientId);  
    }//GEN-LAST:event_findVitalsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable docVitalsTable;
    private javax.swing.JButton findVitalsBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> selPatientCBox;
    // End of variables declaration//GEN-END:variables
}
