/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.LabJPanels;

import Business.Business;
import Lab.Test;
import Lab.TestDirectory;
import Lab.Vaccination;
import Lab.VaccinationDirectory;
import UI.MainJFrame;
import UserAccount.UserAccount;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thran
 */
public class LabTestJFrame extends javax.swing.JPanel {

    /**
     * Creates new form LabTestJFrame
     */
    Business business;
    UserAccount useraccount;
    MainJFrame main;
    TestDirectory testDir;
    DefaultTableModel testTableModel;
    
    public LabTestJFrame(Business business, UserAccount useraccount) {
       initComponents();
        this.business=business;
       this.useraccount=useraccount;
       this.testTableModel = (DefaultTableModel) testsJTable.getModel();
       
       this.setVisible(true);
       
       displayTests();
    }
        
        private void displayTests() {
        
        ArrayList<Test> test = this.business.getTestDir().getLabTestList();
        testTableModel.setRowCount(0);
        for (Test t : test) {
            Object[] row = new Object[2];
            row[0] = t.getTestName();
            row[1] = t.getTestPrice();
            testTableModel.addRow(row);
        }
        

        }
        
        
    
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        testsJTable = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        testsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Test Name", "Price"
            }
        ));
        jScrollPane1.setViewportView(testsJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 440, 130));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new LabJFrame(business, useraccount);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable testsJTable;
    // End of variables declaration//GEN-END:variables
}
