/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.LabJPanels;

import Business.Business;
import Lab.LabTechnician;
import Lab.LabTechnicianDirectory;
import Role.LabTechnicianRole;
import UI.MainJFrame;
import UserAccount.UserAccount;
import javax.swing.JOptionPane;

/**
 *
 * @author thran
 */
public class LabTechnicianRegistrationJFrame extends javax.swing.JFrame {

    /**
     * Creates new form LabTechnicianRegistrationJFrame
     */
    Business business;
    public LabTechnicianRegistrationJFrame() {
        initComponents();
    }
    public LabTechnicianRegistrationJFrame(Business business) {
            initComponents();
            this.setVisible(true);
            this.business = business;
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        labFirstName = new javax.swing.JTextField();
        labLastName = new javax.swing.JTextField();
        labEmail = new javax.swing.JTextField();
        labPhone = new javax.swing.JTextField();
        labAddress = new javax.swing.JTextField();
        labUserName = new javax.swing.JTextField();
        labPassword = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("First Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        jLabel2.setText("Last Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        jLabel3.setText("Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        jLabel4.setText("Phone");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        jLabel5.setText("Address");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        jLabel6.setText("UserName");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, -1));

        jLabel7.setText("Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, -1));

        btnRegister.setText("REGISTER");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, -1));

        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, -1, -1));
        getContentPane().add(labFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 60, -1));
        getContentPane().add(labLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 60, -1));
        getContentPane().add(labEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 60, -1));
        getContentPane().add(labPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 60, -1));
        getContentPane().add(labAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 60, -1));
        getContentPane().add(labUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 60, -1));
        getContentPane().add(labPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 60, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        String firstName = labFirstName.getText();
        String lastName = labLastName.getText();
        String phone = labPhone.getText();
        String email = labEmail.getText();
        String address = labAddress.getText();
        String userName = labUserName.getText();
        String password = labPassword.getText();

        LabTechnicianDirectory lt = this.business.getLabTechnicians();
        LabTechnician l = lt.addTechnician(firstName, lastName, email, address, phone);

        //create a useraccount and add it to the top level dir
        UserAccount ua = new UserAccount();
        ua.setUsername(userName);
        ua.setPassword(password);
        ua.setRole(new LabTechnicianRole())
        ;
        ua.setPersonId(l.getId());
        

        this.business.getTopLevelUserAccountDirectory().getUseraccountList().add(ua);

        JOptionPane.showMessageDialog(null, "Registration successfull! Please go back to the login page to access your profile.");
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MainJFrame(business);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LabTechnicianRegistrationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LabTechnicianRegistrationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LabTechnicianRegistrationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LabTechnicianRegistrationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LabTechnicianRegistrationJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField labAddress;
    private javax.swing.JTextField labEmail;
    private javax.swing.JTextField labFirstName;
    private javax.swing.JTextField labLastName;
    private javax.swing.JTextField labPassword;
    private javax.swing.JTextField labPhone;
    private javax.swing.JTextField labUserName;
    // End of variables declaration//GEN-END:variables
}
